In [1]:
import pandas as pd
import numpy as np
import os

In [4]:
SAVE_DIR = os.path.abspath("../../../prediction_model_tf2/practicum_data/P100_ms_cb")

## Convolutional Layers

In [3]:
dfConv_P100CLIE = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_P100CLIE.pkl'))
dfConv_P100CLIE['peak_performance'] = 14900
dfConv_P100CLIE['IO'] = 15.90
dfConv_P100CLIE['bandwidth'] = 732
dfConv_P100CLIE['cores'] = 3584
dfConv_P100CLIE['clock'] = 1329

dfConv_P100SXM2 = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_P100SXM2.pkl'))
dfConv_P100SXM2['peak_performance'] = 14805
dfConv_P100SXM2['IO'] = 15.90
dfConv_P100SXM2['bandwidth'] = 721
dfConv_P100SXM2['cores'] = 3584
dfConv_P100SXM2['clock'] = 1481

dfConv_K80 = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_K80.pkl'))
dfConv_K80['peak_performance'] = 5591 
dfConv_K80['IO'] = 12
dfConv_K80['bandwidth'] = 240
dfConv_K80['cores'] = 2496
dfConv_K80['clock'] = 824 

dfConv_M40 = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_M40.pkl'))
dfConv_M40['peak_performance'] = 8071 
dfConv_M40['IO'] = 15.75
dfConv_M40['bandwidth'] = 289
dfConv_M40['cores'] = 3072
dfConv_M40['clock'] = 1114 

dfConv = pd.concat([dfConv_P100CLIE, dfConv_P100SXM2, dfConv_M40, dfConv_K80])

In [15]:
dfConv_P100CLIE = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_P100_ms_cb.pkl'))
dfConv_P100CLIE['peak_performance'] = 14900
dfConv_P100CLIE['IO'] = 15.90
dfConv_P100CLIE['bandwidth'] = 732
dfConv_P100CLIE['cores'] = 3584
dfConv_P100CLIE['clock'] = 1329

In [16]:
dfConv = dfConv_P100CLIE
dfConv

,batchsize,matsize,kernelsize,channels_in,channels_out,strides,padding,precision,use_bias,gpu_count,...,opt_SGD,act_None,act_relu,act_sigmoid,act_tanh,peak_performance,IO,bandwidth,cores,clock
0,64,177,5,17,45,3,0,32,0,2,...,0,1,0,0,0,14900,15.9,732,3584,1329
1,49,254,4,2,16,3,1,32,0,2,...,1,0,1,0,0,14900,15.9,732,3584,1329
2,11,402,5,13,5,3,1,32,0,2,...,0,1,0,0,0,14900,15.9,732,3584,1329
3,8,279,4,33,19,3,1,32,1,2,...,1,0,0,0,1,14900,15.9,732,3584,1329
4,55,233,1,30,7,1,1,32,1,2,...,0,0,0,1,0,14900,15.9,732,3584,1329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,34,442,5,15,2,4,1,32,0,2,...,0,0,0,0,1,14900,15.9,732,3584,1329
996,39,335,2,12,10,4,0,32,1,2,...,0,0,0,1,0,14900,15.9,732,3584,1329
997,64,96,6,37,96,4,1,32,1,2,...,0,0,0,0,1,14900,15.9,732,3584,1329
998,23,314,3,25,23,1,1,32,1,2,...,0,1,0,0,0,14900,15.9,732,3584,1329
999,38,73,7,20,97,2,0,32,0,2,...,0,0,0,1,0,14900,15.9,732,3584,1329

In [10]:
#dfConv = dfConv[dfConv['batchsize']<33]

In [17]:
dfConv.to_pickle(os.path.join(SAVE_DIR,'Data_convolution_P100_ms_cb.pkl'))

In [10]:
dfConv[['timeUsed_median']]

     timeUsed_median
0           0.760223
1           0.013633
2           0.426030
3           0.010792
4           0.046726
..               ...
995         0.010544
996         0.096867
997         0.017334
998         0.536943
999         0.774911

[3000 rows x 1 columns]