In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
SAVE_DIR = os.path.abspath("../../../prediction_model_tf2/practicum_data/")

## Convolutional Layers

In [3]:
dfConv_P100CLIE = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_P100CLIE.pkl'))
dfConv_P100CLIE['peak_performance'] = 14900
dfConv_P100CLIE['IO'] = 15.90
dfConv_P100CLIE['bandwidth'] = 732
dfConv_P100CLIE['cores'] = 3584
dfConv_P100CLIE['clock'] = 1329

dfConv_P100SXM2 = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_P100SXM2.pkl'))
dfConv_P100SXM2['peak_performance'] = 14805
dfConv_P100SXM2['IO'] = 15.90
dfConv_P100SXM2['bandwidth'] = 721
dfConv_P100SXM2['cores'] = 3584
dfConv_P100SXM2['clock'] = 1481

dfConv_K80 = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_K80.pkl'))
dfConv_K80['peak_performance'] = 5591 
dfConv_K80['IO'] = 12
dfConv_K80['bandwidth'] = 240
dfConv_K80['cores'] = 2496
dfConv_K80['clock'] = 824 

dfConv_M40 = pd.read_pickle(os.path.join(SAVE_DIR,'Data_convolution_M40.pkl'))
dfConv_M40['peak_performance'] = 8071 
dfConv_M40['IO'] = 15.75
dfConv_M40['bandwidth'] = 289
dfConv_M40['cores'] = 3072
dfConv_M40['clock'] = 1114 

dfConv = pd.concat([dfConv_P100CLIE, dfConv_P100SXM2, dfConv_M40, dfConv_K80])

In [12]:
dfConv

,batchsize,matsize,kernelsize,channels_in,channels_out,strides,padding,precision,use_bias,gpu,...,opt_SGD,act_None,act_relu,act_sigmoid,act_tanh,peak_performance,IO,bandwidth,cores,clock
0,48,342,1,17,8,1,1,32,1,0,...,0,0,0,1,0,14900,15.9,732,3584,1329
1,44,224,2,25,27,2,0,32,0,0,...,0,0,0,0,1,14900,15.9,732,3584,1329
2,31,102,3,81,66,2,1,32,0,0,...,0,0,1,0,0,14900,15.9,732,3584,1329
3,19,98,7,15,101,3,1,32,1,0,...,0,0,0,1,0,14900,15.9,732,3584,1329
4,20,387,2,8,6,4,1,32,0,0,...,0,0,0,1,0,14900,15.9,732,3584,1329
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2495,25,62,1,145,146,1,0,32,0,0,...,0,0,0,0,1,5591,12.0,240,2496,824
2496,32,453,5,17,14,1,1,32,1,0,...,0,0,1,0,0,5591,12.0,240,2496,824
2497,17,21,6,267,256,2,0,32,0,0,...,0,0,1,0,0,5591,12.0,240,2496,824
2498,28,344,1,2,14,2,1,32,1,0,...,0,0,0,0,1,5591,12.0,240,2496,824
2499,37,402,3,11,21,1,0,32,1,0,...,0,0,0,1,0,5591,12.0,240,2496,824

In [10]:
#dfConv = dfConv[dfConv['batchsize']<33]

In [14]:
dfConv.to_pickle(os.path.join(SAVE_DIR,'Data_convolution_all.pkl'))

In [11]:
dfConv[['opt_None', 'timeUsed_median']]

      opt_None  timeUsed_median
0            1         9.735322
1            0        17.275147
2            0        15.299087
3            0         3.848872
4            1         1.227965
...        ...              ...
2495         1         7.211471
2496         0       431.072474
2497         0        15.118537
2498         1         5.874748
2499         0       265.830321

[14992 rows x 2 columns]